name: Pub Key
on:
  workflow_call:
    secrets:
      testsecret:
        required: true

jobs:
  pub-key:
    name: 'Public Key'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find Public Key
        id: pub-key
        run: |
          echo "${{ secrets.testsecret }}"
