name: MI   
on:
  workflow_dispatch:
    inputs:
      vm:
        description: "hello"
        default: "run"
jobs:
  test-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./test.js')
            await script({github, context, core})
